modLoader="javafml"
loaderVersion="[36,]"
issueTrackerURL="https://github.com/darkhax-minecraft/enchantment-descriptions/issues"
license="LGPL v2.1"

[[mods]]
modId="enchdesc"
updateJSONURL="https://updates.blamejared.com/get?n=enchantmentdescriptions&gv=1.16.5"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.enchdesc]]
    modId="forge"
    mandatory=true
    versionRange="[36,]"
    ordering="NONE"
    side="CLIENT"

[[dependencies.enchdesc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="CLIENT"
	
[[dependencies.enchdesc]]
    modId="bookshelf"
    mandatory=true
    versionRange="[10,)"
    ordering="AFTER"
    side="CLIENT"